### ISSUE TITLE
Help for GHE support and Catalog-Refresh in own instance

### ISSUE THREAD

**Issue by wwitteriii** [tektoncd/hub#169]
I am trying to stand up tekton-hub in openshift 4.6.9, in a proxy'd environment.

I am running into the following issues and would like assistance specifically with catalog-refresh:

First:  GH oauth appears to only support github.com, but when attempting to use on-prem Github Enterprise, I get an invalid authorization error as the oauth app in GHE is not in GH.  

Second:  catalog refresh is failing with "invalid-scopes" or "unauthorized user". despite having customized a config.yaml to include my github-user with full permissions, and setting of the JWT.  Perhaps my issue is that the db entry is not being created properly for that user, but I am not finding anything specific in documentation to assist with getting an additional user added to catalog-refresh scope.

The overall goal that I am working towards is attempting to get our own instance of tekton-hub created so we can have it source from our own internal catalog repo so we control a curated list of tasks/pipelines specific to our environment...however at this point I can't get our instance to even display the existing catalog from "github.com/tektoncd/catalog" properly.

**Comment by vinamra28** [comment]
Hi @wwitteriii,

> Second: catalog refresh is failing with "invalid-scopes" or "unauthorized user". despite having customized a config.yaml to include my github-user with full permissions, and setting of the JWT. Perhaps my issue is that the db entry is not being created properly for that user, but I am not finding anything specific in documentation to assist with getting an additional user added to catalog-refresh scope.
> 
> The overall goal that I am working towards is attempting to get our own instance of tekton-hub created so we can have it source from our own internal catalog repo so we control a curated list of tasks/pipelines specific to our environment...however at this point I can't get our instance to even display the existing catalog from "github.com/tektoncd/catalog" properly.

As such there is no better solution for now but we have tried documenting something in the deployment doc and raised a PR #173 for the same. We'll try to improve this asap.
Feedbacks are most welcome!

/kind feature
