### ISSUE TITLE
API: /query endpoint with query `tags=` returns `resource not found`

### ISSUE THREAD

**Issue by vinamra28** [tektoncd/hub#170]
# Expected Behavior

When we hit the API `https://api.hub.tekton.dev/query?tags=` we should be getting the list of resources such as `orka-full` Task which is not having any tag.

# Actual Behavior

When we hit the API we get the following response
```json
{
  "name": "not-found",
  "id": "OI8VwIgR",
  "message": "resource not found",
  "temporary": false,
  "timeout": false,
  "fault": false
}
```

# Steps to Reproduce the Problem

1. Go to any REST client from where you can make the GET request
2. Hit `https://api.hub.tekton.dev/query?tags=`
3. Check the response. The response doesn't contain resources which are not having tags such as `orka-full`.

# Additional Info

- UI Screenshots(if applicable)

  ```
  (Add ui screenshots here)
  ```

**Comment by khrm** [comment]
/reopen
/remove-lifecycle rotten
/lifecycle frozen
This bugs need to be fixed.
