### ISSUE TITLE
Tasks not indexed in hub.tekton.dev

### ISSUE THREAD

**Issue by rhybrillou** [tektoncd/hub#1739]
# Expected Behavior

Tasks rhacs-deployment-check, rhacs-image-check, rhacs-image-scan can be found on https://hub.tekton.dev

# Actual Behavior

Searching for rhacs on hub.tekton.dev shows 5 tasks (including stackrox-* tasks), but these don't include the rhacs-* ones.

# Steps to Reproduce the Problem

1. Go to https://hub.tekton.dev
2. enter rhacs in the search box at the top right
3. look at the results

# Additional Info

- UI Screenshots(if applicable)
![Screenshot 2024-06-04 at 13 57 07](https://github.com/tektoncd/hub/assets/91869377/ba455167-c3cf-4d97-a337-227c5f151ffa)

  ```
  (Add ui screenshots here)
  ```

**Comment by PuneetPunamiya** [comment]
Now all the tasks are available on Hub
Hence closing this issue
