### ISSUE TITLE
add UI link to task/pipeline `tkn hub search` command output

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/hub#175]
### Feature request

The description in the current output of `tkn hub search` command output is very less, it would be helpful if the output also contains the UI link to the task

### Use case
When a user searches for the task using `tkn hub search` he will understand the usage, parameters required and other things by visiting the link before installing the task

**Comment by SM43** [comment]
we can provide the UI link. but I think the user shouldn't have to move away from the console for any info. We should display that in some commands.
for the above case, we have an `info` command which displays the full description. or `get` command which prints the yaml on the console. for readme, we don't have any command but we can add a flag in get `--readme`
wdyt?
