### ISSUE TITLE
Redirect HTTP to HTTPs for hub.tekton.dev

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/hub#177]
### Feature request

We should not serve http:// , and redirect instead to https://

### Use case

It will not look nice when using HTTP, browsers will mark it as insecure.

![image](https://user-images.githubusercontent.com/2205608/106140160-4e1cc980-6166-11eb-8b50-4238ad837312.png)

**Comment by sm43** [comment]
done in #291  
/close
