### ISSUE TITLE
Replace preview URL in README with the non preview URL

### ISSUE THREAD

**Issue by SM43** [tektoncd/hub#182]
# Expected Behavior
The readme should point to hub's non-preview URL i.e hub.tekton.dev as hub is out of preview.

# Actual Behavior
The readme currently has 
```
Currently, Hub is launched as a preview hub-preview.tekton.dev 
```

**Comment by 96RadhikaJadhav** [comment]
@SM43 Can I work on it?

**Comment by vinamra28** [comment]
yeah sure. Please go ahead :)
