### ISSUE TITLE
`tkn hub search <tag-name>` not working properly

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/hub#234]
# Expected Behavior
`tkn hub search` should show valid error message asking for user to use `--tag` flag to search for tasks/pipelines with tag

# Actual Behavior
`tkn hub search` shows an error message as `Error: please specify a name, tag or a kind to search` which makes user to to run `tkn hub search <tag-name>` instead of `tkn hub search --tag <tag-name>`

# Steps to Reproduce the Problem

1. Run `tkn hub search`
2. Observe the error message

# Additional Info
Command execution log below
```
$ tkn hub search 
Error: please specify a name, tag or a kind to search
```

- UI Screenshots(if applicable)

  ```
  
  ```

**Comment by sm43** [comment]
the error message is updated.
/close
