### ISSUE TITLE
Support for GHE authentication

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/hub#248]
### Feature request

Deploy the Tekton Hub connected to GitHub Enterprise for user authentication.

### Use case

I'm setting up a Tekton Catalog and Hub in my org, and I would like to connect the user accounts to the internal GHE.

### Additional Info

Today Tekton Hub relies on [`react-github-login`](https://www.npmjs.com/package/react-github-login) that provides GitHub authentication. We could use [`react-ghe-login`](https://www.npmjs.com/package/react-ghe-login) instead that supports both.

**Comment by afrittoli** [comment]
Some of the changes needed: https://github.com/tektoncd/hub/compare/main...afrittoli:ghe_nonroot_icr
This replaces github for ghe, so we would instead need some config options to support both.

**Comment by sm43** [comment]
Done in #275 
/close
