### ISSUE TITLE
CLI: Remove the space if there are no tags for a task 

### ISSUE THREAD

**Issue by PuneetPunamiya** [tektoncd/hub#254]
# Expected Behavior

If there are no tags for a resource then there should be no space left between rating and install command in the UI

For e.g.
```
╰─ tkn hub info task orka-full 
📦 Name: orka-full 

📌 Version: 0.1 (Latest)

📖 Description: With this Task, you can use your Orka environment to run macOS
 builds and macOS-related testing from your Tekton pipelines. This Task creates
 a VM template with the specified configuration, deploys a VM instance from it,
 and then cleans up the environment. All operations in this `Task` are
 performed against an Orka environment.

🗒  Minimum Pipeline Version: 0.16.0

⭐ ️Rating: 0

⚒ Install Command:
  tkn hub install task orka-full
```  

# Actual Behavior

There's an extra space if there are no tags for a resource

For e.g.
```
╰─ tkn hub info task orka-full 
📦 Name: orka-full 

📌 Version: 0.1 (Latest)

📖 Description: With this Task, you can use your Orka environment to run macOS
 builds and macOS-related testing from your Tekton pipelines. This Task creates
 a VM template with the specified configuration, deploys a VM instance from it,
 and then cleans up the environment. All operations in this `Task` are
 performed against an Orka environment.

🗒  Minimum Pipeline Version: 0.16.0

⭐ ️Rating: 0



⚒ Install Command:
  tkn hub install task orka-full
```

**Comment by amino19** [comment]
@PuneetPunamiya : Can I get the resources to go through? I want to wok on this (if permits) :slightly_smiling_face:

**Comment by PuneetPunamiya** [comment]
@amino19  Thanks for showing interest
You need to redirect to the `api` directory and create the binary using `go build ./cmd/tkn-hub`
Also to find the cli code you can see the code in `pkg` directory there is a directory called [cli](https://github.com/tektoncd/hub/tree/main/api/pkg/cli) 

Hope this helps you

**Comment by amino19** [comment]
@PuneetPunamiya : Thanks for response back with great shot! This details definitely works for me, I doesn't have much premiere knowledge about this, but will love to hit a try with a PR, hope you guide me there. :slightly_smiling_face:

**Comment by PuneetPunamiya** [comment]
@amino19  Yep sure will be happy to help
I'll assign this issue to you 😉 
/assign @amino19

**Comment by amino19** [comment]
@PuneetPunamiya : I went through approx all files, got <a href= "https://github.com/tektoncd/hub/blob/main/api/pkg/cli/cmd/info/testdata/TestPipelineTask_MultiLineDescription.golden"> this </a>; Shall I have to change this or custom?

**Comment by PuneetPunamiya** [comment]
@amino19  Apologies for late reply, I think based on the code you write this will not change but you'll have to add a test which has no tags
