### ISSUE TITLE
Authentication is not working on Firefox browser

### ISSUE THREAD

**Issue by pratap0007** [tektoncd/hub#258]
# Expected Behavior
If User's authentication is successful then user should redirect  to Hub's home page otherwise it should pop-up the error on Hub
# Actual Behavior
While doing Authentication it opens hub application in the new tab and authentication gets fail

# Steps to Reproduce the Problem

1.Open Hub on Firefox browser : https://hub.tekton.dev/
2.Try to login 
3.

# Additional Info

- UI Screenshots(if applicable)

  ```
  (Add ui screenshots here)
  ```

**Comment by vinamra28** [comment]
@pratap0007, I guess the auth is working properly now on firefox. Can you please cross-check once again and close this issue if it is resolved?

**Comment by pratap0007** [comment]
Yes,It is resolved now and closing the issue.
