### ISSUE TITLE
Hub UI displays username in lower case even if actual GitHub username contains both lower and upper case

### ISSUE THREAD

**Issue by vinamra28** [tektoncd/hub#288]
# Expected Behavior

Hub UI should display the username in the same way the user has kept in Github. Example my github username is fooBar but Hub UI displays my username as foobar.

# Actual Behavior

Hub UI should display the username in same way we have in Github. example my Github username is fooBar so Hub UI should also display fooBar

# Steps to Reproduce the Problem

1. Have a github username such that it has both lowercase and uppercase letters.
2. Login into Hub UI and see the username on top right corner.

# Additional Info

Probable place where we need to fix is 
https://github.com/tektoncd/hub/blob/9f058519d26936d9eaf8d729cce256e1bae87192/api/pkg/service/auth/auth.go#L135
and the query needs to be updated as
https://github.com/tektoncd/hub/blob/9f058519d26936d9eaf8d729cce256e1bae87192/api/pkg/service/auth/auth.go#L126

/good-first-issue

**Comment by kk-r** [comment]
@vinamra28 Submitted PR - #295  Thanks for all the details. It really helpful!

 I'd like to mention that I have found additional case when username in database is mixed-case and user changed to lowercase in GitHub(as per GitHub `fooBar` and  `foobar` both are same.). So w need to handle this case by lowercase the value in our database and check with username from GitHub. 
 
`Where("LOWER(github_login) = ? or github_login = ?", strings.ToLower(ghUser.GetLogin()), ghUser.GetLogin())`

I'm new to this community. If there is anything missing or need to cover, please let me know. Thanks again! :)
