### ISSUE TITLE
`tkn hub` doesn't recognises Tekton Pipelines `devel` version

### ISSUE THREAD

**Issue by PuneetPunamiya** [tektoncd/hub#312]
# Expected Behavior

` tkn hub` should recognise tekton pipelines `devel` version which will allow to install the task using `tkn hub install` command

# Actual Behavior

`tkn hub` doesn't recognises Tekton Pipelines `devel` version

# Steps to Reproduce the Problem

1. Install Tekton Pipelines manually using `ko apply -f config` (hope you have cloned the [tektoncd/pipelines](https://github.com/tektoncd/pipeline) repo
2.  On running the `tkn version` command you should see the following result 

      ```
      $ tkn version
      Client version: 0.19.0
      Pipeline version: devel
       ```
       
3. Now running the `tkn hub` install you will get the following error 
    ```
    $ tkn hub install task buildah                 
    Error: Task buildah(0.2) requires Tekton Pipelines min version v0.17.0 but found devel
    ```

**Comment by vinamra28** [comment]
Resolved in #333
/close
