### ISSUE TITLE
Default hub items to "community" until we add more tests

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/hub#34]
In the current tekton hub preview (https://ui-tekton-hub.apps.openshift-web.p0s5.p1.openshiftapps.com/) (which looks AMAZING btw :D) all of the tasks we currently have in the catalog defualt to "official" support tier:

![image](https://user-images.githubusercontent.com/432502/87086965-49abb600-c200-11ea-8484-a3b6ab7f2bf6.png)

Since we haven't yet put in place the level of testing we want to for the official and verified support tiers (https://github.com/tektoncd/catalog/issues/373) let's default everything to "community" for now, and we can evaluate and update Tasks as we go and promote to official and verified.

**Comment by PuneetPunamiya** [comment]
Done!
