### ISSUE TITLE
Selecting a Card Does Not Scroll to the Top

### ISSUE THREAD

**Issue by andrewballantyne** [tektoncd/hub#46]
When testing out https://hub-preview.tekton.dev/ I noticed if I scroll down the page and select a card, it does not scroll back to the top of the window and thus sorta just shows no content. I wondered if it was a loading issue but it turns out my scroll position was just kept between the two pages.

**Comment by SM43** [comment]
This has been partially fixed and deployed to hub preview.

**Comment by andrewballantyne** [comment]
@SM43 I did a quick re-test... I see the original issue I logged completely solved. What would you be referring to is "partially fixed"?

**Comment by sthaha** [comment]
It is a partial fix because you can see the same occur on other (smaller 1280x800) screen resolutions which I am not sure how that even relates to responsive layout.

**Comment by andrewballantyne** [comment]
Ah, you have responsive layout issues for sure - didn't test on a "smaller" screen. I think that is however a different issue. 

You guys are welcome to keep this open, of course, but as the author I'm satisfied with the solution to the original logged issue.

**Comment by andrewballantyne** [comment]
I'm satisfied with my original problem. If the responsive layout issues are still an issue you can log another issue to track that under.
