### ISSUE TITLE
Preview description not showing up for a few tasks at hub

### ISSUE THREAD

**Issue by navidshaikh** [tektoncd/hub#52]
# Expected Behavior
Short/preview description of all the tasks appear on hub.

# Actual Behavior
For a few tasks, description is not showing up at hub.

# Steps to Reproduce the Problem
1. open https://hub-preview.tekton.dev/
2. search or locate tasks viz [kn, curl, aws cli, buildkit]
3. you dont see any description unless you click on the task to find it.

# Additional Info

- Noticed that tasks with full description separated by a single line are not affected.

**Comment by SM43** [comment]
Fixed in Experimental.
/Close
