### ISSUE TITLE
QUESTION - hub.tekton.dev - NexusIQ Task

### ISSUE THREAD

**Issue by BillBensing** [tektoncd/hub#614]
We recently added a task to the Tekton Catalog.  When does the hub.tekton.dev get updated to reflect these additions?

**Comment by PuneetPunamiya** [comment]
In Tekton Hub we internally have a cron job which refreshes the catalog after every 30 min, so whenever a new task is added in the catalog after 30 mins it will be reflected on Hub

**Comment by PuneetPunamiya** [comment]
@BillBensing thanks for bringing this up, so actually the way the task is submitted in the catalog doesn't meet all the requirements mention in [TEP-003](https://github.com/tektoncd/community/blob/main/teps/0003-tekton-catalog-organization.md) and that is why the resource is not been getting added in the database and hence it is not been reflected on hub.tekton.dev. 
There are actual two reason why the resource is not getting added in database and they are
* In the catalog if you see the name of the resource at the directory level is `nexus-lifecycle-scan`  --> https://github.com/tektoncd/catalog/tree/main/task/nexus-lifecycle-scan/0.1 and the name of the resource in the yaml is  `nexus-lifecycle-scan-task` ---> https://github.com/tektoncd/catalog/blob/main/task/nexus-lifecycle-scan/0.1/nexus-lifecycle-scan.yml#L4
* And the second reason for the task not been getting added is currently the extension supported to add  resources is `.yaml` and I  think that is the reason why catlin didn't fail on the catalog ci when the resource was added 

I'll submit a patch for it in catalog  👍🏻

**Comment by PuneetPunamiya** [comment]
I have submitted a patch for this https://github.com/tektoncd/catalog/pull/1060
Thanks 🙂

**Comment by PuneetPunamiya** [comment]
Now you can see the task on hub.tekton.dev --> https://hub.tekton.dev/tekton/task/nexus-lifecycle-scan

**Comment by BillBensing** [comment]
@PuneetPunamiya , thank you very much for pointing me to the mistake!  Also, many more thanks for the patch!

**Comment by BillBensing** [comment]
A good day, I learned what I did wrong.
