### ISSUE TITLE
Add a "type" flag to the "tkn hub" subcommands

### ISSUE THREAD

**Issue by QuanZhang-William** [tektoncd/hub#691]
### Feature request
The Tekton community is working on migrating from the Tekton Hub to the Artifact Hub (https://github.com/tektoncd/hub/issues/667). We'd like to request a new flag `type` (with short flag `t`)  to the [`tkn hub`](https://github.com/tektoncd/cli/blob/main/docs/cmd/tkn_hub.md) subcommand, indicating the type of the Hub to fetch the Tekton Catalogs from.

### Use case
The Tekton Catalogs are surfaced in the [Artifact Hub](https://artifacthub.io/) and the [Tekton Hub](https://hub.tekton.dev/). The new `type` flag can be set to `artifact` or `tekton`, and the corresponding hub APIs should be invoked to fetch the catalogs.

When setting to `tekton`, the default `api-server` flag should be: https://api.hub.tekton.dev.
When setting to `artifact` the default `api-server` flag should be: https://artifacthub.io.

### UI Example

`tkn hub install --type artifact --version 0.8`

### Breakdown

* [x] install: https://github.com/tektoncd/hub/pull/757
* [ ] reinstall
* [ ] upgrade
* [ ] downgrade
* [ ] check-upgrade
* [ ] get
* [ ] info
* [ ] search

**Comment by vinamra28** [comment]
@QuanZhang-William @tektoncd/hub-collaborators listing down all the commands so that we can maintain a track of all the subcommands
- [ ] install
- [ ] reinstall
- [ ] upgrade
- [ ] downgrade
- [ ] check-upgrade
- [ ] get
- [ ] info
- [ ] search
@QuanZhang-William if you are okay, how about we open this for contributions so that if someone wants to contribute then they can have something for contribution?

**Comment by QuanZhang-William** [comment]
> @QuanZhang-William @tektoncd/hub-collaborators listing down all the commands so that we can maintain a track of all the subcommands
> 
> * [ ]  install
> * [ ]  reinstall
> * [ ]  upgrade
> * [ ]  downgrade
> * [ ]  check-upgrade
> * [ ]  get
> * [ ]  info
> * [ ]  search
>   @QuanZhang-William if you are okay, how about we open this for contributions so that if someone wants to contribute then they can have something for contribution?

Definitely! This is exactly what I planned to do. I will first prioritize the functionalities that unblocks [TEP-0079](https://github.com/tektoncd/community/blob/main/teps/0079-tekton-catalog-support-tiers.md#community-and-official-catalogs-in-the-tekton-cli).

Could you please show me how to open this for contributions?

**Comment by QuanZhang-William** [comment]
Implementation in progress. 
/remove-lifecycle stale
