### ISSUE TITLE
Fix OpenAPI - v3 and Swagger generation

### ISSUE THREAD

**Issue by sthaha** [tektoncd/hub#78]
The current swagger and openapi-v3 autogenerated files fail validation when checked against https://apitools.dev/swagger-parser/online/ . 
Lets ensure that these files are valid to allow easier integration of API (server) with external tools

/kind bug

**Comment by sthaha** [comment]
Notes:
    - Goa Examples have same issues in OpenAPI 
    - OpenAPI3 is fixed in 3.2.1 

 But examples needs to be added and descriptions should be detailed...

**Comment by SM43** [comment]
https://github.com/tektoncd/hub/pull/97

/close
