### ISSUE TITLE
Create a monitoring tool that can update slack when https://hub-preview.tekton.dev/ is down

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/hub#82]
### Feature request

Create a tool that will check periodically to make sure https://hub-preview.tekton.dev/ is up and will ping slack if it isn't.

One option is to use https://github.com/bitnami-labs/kubewatch but that's not required.

I think it is reasonable for [tekton build cop responsibilities](https://docs.google.com/document/d/1QJV0z2bMXdz_BZOkBwfxIP1BiktUb8c1lcifwqxF5wg/edit) to at least include making sure this tool is up; what is less clear is who will be responsible for following up if the hub itself is down (could be build cop, could be hub OWNERS).

(Following up on some discussion in the working group)

### Use case

If https://hub-preview.tekton.dev/ was to go down, we want to be able to find out right away. As we figure out the processes around the hub and our SLOs, a great step along the way would be to at least notify folks when there is an outage.

**Comment by bobcatfish** [comment]
@SM43 I finally made this issue, sorry for the delay! I think you might already be looking into this?

**Comment by SM43** [comment]
@bobcatfish NP. Thanks for creating the issue. I have started looking into this :)
